import { AIHubModel } from '../types';

export const QUALCOMM_AI_HUB_MODELS: AIHubModel[] = [
  {
    id: 'fastvit_s12',
    name: 'FastViT-S12 (UI Element Detection)',
    type: 'vision',
    inputShape: '[1, 3, 640, 640]',
    precision: 'INT8',
    targetDevice: 'Snapdragon X Elite',
    targetRuntime: 'QNN (QnnHtp.dll)',
    npuLatencyMs: 11.2,
    cpuLatencyMs: 84.6,
    speedup: '7.6x faster',
    powerWatts: 4.2,
    hvxUtil: 48,
    hmxUtil: 46,
    description: 'Ultra-low latency structural vision transformer quantized via Qualcomm AIMET for instantaneous screen parsing and accessibility element tagging.',
  },
  {
    id: 'yolov8n_screen',
    name: 'YOLOv8-nano (Adaptive Bounding Reticle)',
    type: 'vision',
    inputShape: '[1, 3, 640, 640]',
    precision: 'FP16',
    targetDevice: 'Snapdragon X Elite',
    targetRuntime: 'QNN (QnnHtp.dll)',
    npuLatencyMs: 14.8,
    cpuLatencyMs: 98.2,
    speedup: '6.6x faster',
    powerWatts: 4.8,
    hvxUtil: 52,
    hmxUtil: 42,
    description: 'Continuous real-time interactive UI widget and cursor tracking with zero-copy DMA frame ingestion from Windows Desktop Duplication API.',
  },
  {
    id: 'gemma_2b_instruct',
    name: 'Gemma-2B-Instruct (On-Device SLM)',
    type: 'slm',
    inputShape: '[1, 2048] (KV-Cache)',
    precision: 'INT8',
    targetDevice: 'Snapdragon X Elite',
    targetRuntime: 'QNN (QnnHtp.dll)',
    npuLatencyMs: 22.4,
    cpuLatencyMs: 165.0,
    speedup: '7.4x faster',
    powerWatts: 6.5,
    hvxUtil: 38,
    hmxUtil: 64,
    description: 'Quantized Small Language Model running 100% locally on Hexagon HTP for screen summarization, voice intent parsing, and assistive prompt synthesis.',
  },
  {
    id: 'whisper_tiny_en',
    name: 'Whisper-Tiny (Real-Time Voice Intent)',
    type: 'audio',
    inputShape: '[1, 80, 3000]',
    precision: 'INT8',
    targetDevice: 'Snapdragon X Elite',
    targetRuntime: 'QNN (QnnHtp.dll)',
    npuLatencyMs: 8.5,
    cpuLatencyMs: 62.0,
    speedup: '7.3x faster',
    powerWatts: 3.1,
    hvxUtil: 55,
    hmxUtil: 40,
    description: 'On-device streaming speech recognition for hands-free accessibility control and ambient desktop voice commands.',
  },
];
